from graph.models.types import Status, HypothesisStatus, Category, EdgeType, GPUType
from graph.models.nodes import Experiment, Technique, Hypothesis, Result, Synthesis, Run, Agent
from graph.models.edges import (
    BaseEdge,
    Tried,
    ImprovedFrom,
    FailedFrom,
    MotivatedBy,
    Invalidates,
    CorrelatedWith,
    LedTo,
    RanBy,
    RanOn,
    BeatGlobal,
    BeatOwn,
    Tested,
    Produced,
    Challenged,
    PartOf,
    Contradicts,
    Refines,
    SynthesizedFrom,
    SupportsSynthesis,
    ContradictsSynthesis,
)
